sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # decrypt the account private key file (~IAM)
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # set up google cloud
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # google cli to also install the kubectl in travis
  - gcloud components update kubectl
  # authorize gcloud
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud set project multi-k8s-293414
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dwemer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dwemer/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master